In [2]:
import pandas as pd

In [3]:
train_df = pd.read_parquet("train.parquet")
test_df = pd.read_parquet("test.parquet")

In [6]:
feature_names = train_df.drop(columns=["label"]).columns.tolist()
print(feature_names)

['Header_Length', 'Protocol Type', 'Duration', 'Rate', 'Srate', 'Drate', 'fin_flag_number', 'syn_flag_number', 'rst_flag_number', 'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number', 'ack_count', 'syn_count', 'fin_count', 'rst_count', 'HTTP', 'HTTPS', 'DNS', 'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP', 'IPv', 'LLC', 'Tot sum', 'Min', 'Max', 'AVG', 'Std', 'Tot size', 'IAT', 'Number', 'Magnitue', 'Radius', 'Covariance', 'Variance', 'Weight']


In [7]:
for col in feature_names:
    python_name = col.lower().replace(" ", "_")
    print(f'    {python_name}: float = Field(..., alias="{col}")')

    header_length: float = Field(..., alias="Header_Length")
    protocol_type: float = Field(..., alias="Protocol Type")
    duration: float = Field(..., alias="Duration")
    rate: float = Field(..., alias="Rate")
    srate: float = Field(..., alias="Srate")
    drate: float = Field(..., alias="Drate")
    fin_flag_number: float = Field(..., alias="fin_flag_number")
    syn_flag_number: float = Field(..., alias="syn_flag_number")
    rst_flag_number: float = Field(..., alias="rst_flag_number")
    psh_flag_number: float = Field(..., alias="psh_flag_number")
    ack_flag_number: float = Field(..., alias="ack_flag_number")
    ece_flag_number: float = Field(..., alias="ece_flag_number")
    cwr_flag_number: float = Field(..., alias="cwr_flag_number")
    ack_count: float = Field(..., alias="ack_count")
    syn_count: float = Field(..., alias="syn_count")
    fin_count: float = Field(..., alias="fin_count")
    rst_count: float = Field(..., alias="rst_count")
    http: float = Field(...

In [11]:
train_df["canonical_label"] = train_df["label"].str.rstrip("0123456789")
test_df["canonical_label"] = test_df["label"].str.rstrip("0123456789")

In [12]:
train_df["canonical_label"].value_counts()

canonical_label
TCP_IP-DDoS-UDP            1635956
TCP_IP-DDoS-ICMP           1537476
TCP_IP-DDoS-TCP             804465
TCP_IP-DDoS-SYN             801962
TCP_IP-DoS-UDP              566950
TCP_IP-DoS-SYN              441903
TCP_IP-DoS-ICMP             416292
TCP_IP-DoS-TCP              380384
Benign                      192732
MQTT-DDoS-Connect_Flood     173036
Recon-Port_Scan              83981
MQTT-DoS-Publish_Flood       44376
MQTT-DDoS-Publish_Flood      27623
Recon-OS_Scan                16832
ARP_Spoofing                 16047
MQTT-DoS-Connect_Flood       12773
MQTT-Malformed_Data           5130
Recon-VulScan                 2173
Recon-Ping_Sweep               740
Name: count, dtype: int64

In [13]:
category_map = {
    "TCP_IP-DDoS-UDP": "DDoS",
    "TCP_IP-DDoS-ICMP": "DDoS",
    "TCP_IP-DDoS-TCP": "DDoS",
    "TCP_IP-DDoS-SYN": "DDoS",
    "TCP_IP-DoS-UDP": "DoS",
    "TCP_IP-DoS-SYN": "DoS",
    "TCP_IP-DoS-ICMP": "DoS",
    "TCP_IP-DoS-TCP": "DoS",
    "MQTT-DDoS-Connect_Flood": "MQTT",
    "MQTT-DDoS-Publish_Flood": "MQTT",
    "MQTT-DoS-Publish_Flood": "MQTT",
    "MQTT-DoS-Connect_Flood": "MQTT",
    "MQTT-Malformed_Data": "MQTT",
    "Recon-Port_Scan": "Recon",
    "Recon-OS_Scan": "Recon",
    "Recon-VulScan": "Recon",
    "Recon-Ping_Sweep": "Recon",
    "ARP_Spoofing": "Spoofing",
    "Benign": "Benign",
}

train_df["category"] = train_df["canonical_label"].map(category_map)
test_df["category"] = test_df["canonical_label"].map(category_map)

In [14]:
train_df["category"].isna().sum()

np.int64(0)

In [8]:
train_df["category"].value_counts()

category
DDoS        4779859
DoS         1805529
MQTT         262938
Benign       192732
Recon        103726
Spoofing      16047
Name: count, dtype: int64

In [9]:
train_df.columns

Index(['Header_Length', 'Protocol Type', 'Duration', 'Rate', 'Srate', 'Drate',
       'fin_flag_number', 'syn_flag_number', 'rst_flag_number',
       'psh_flag_number', 'ack_flag_number', 'ece_flag_number',
       'cwr_flag_number', 'ack_count', 'syn_count', 'fin_count', 'rst_count',
       'HTTP', 'HTTPS', 'DNS', 'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP',
       'DHCP', 'ARP', 'ICMP', 'IGMP', 'IPv', 'LLC', 'Tot sum', 'Min', 'Max',
       'AVG', 'Std', 'Tot size', 'IAT', 'Number', 'Magnitue', 'Radius',
       'Covariance', 'Variance', 'Weight', 'label', 'canonical_label',
       'category'],
      dtype='object')

In [10]:
train_df.head()

,Header_Length,Protocol Type,Duration,Rate,Srate,Drate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,...,IAT,Number,Magnitue,Radius,Covariance,Variance,Weight,label,canonical_label,category
0,866.6,10.4,64.0,45722.390222,45722.390222,0.0,0.0,0.0,0.0,0.3,...,1.694026e+08,5.5,16.963645,213.095221,66236.076476,0.9,38.5,ARP_Spoofing,ARP_Spoofing,Spoofing
1,3934.3,12.6,131.2,35708.799475,35708.799475,0.0,0.0,0.0,0.0,0.3,...,1.694026e+08,13.5,30.885371,708.919620,251721.126817,1.0,244.6,ARP_Spoofing,ARP_Spoofing,Spoofing
2,5592.8,12.6,97.6,66.403506,66.403506,0.0,0.0,0.0,0.0,0.3,...,1.361110e-02,5.5,21.787095,290.694475,84028.647525,0.9,38.5,ARP_Spoofing,ARP_Spoofing,Spoofing
3,9303.6,14.8,80.8,51.201280,51.201280,0.0,0.0,0.0,0.0,0.1,...,1.694026e+08,13.5,26.954506,597.046005,178453.001691,1.0,244.6,ARP_Spoofing,ARP_Spoofing,Spoofing
4,8592.4,12.6,98.6,42.706455,42.706455,0.0,0.0,0.0,0.0,0.2,...,1.393099e-02,5.5,24.255148,375.324132,80115.110731,0.9,38.5,ARP_Spoofing,ARP_Spoofing,Spoofing


In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [16]:
print(train_df.columns.tolist())
print(test_df.columns.tolist())

['Header_Length', 'Protocol Type', 'Duration', 'Rate', 'Srate', 'Drate', 'fin_flag_number', 'syn_flag_number', 'rst_flag_number', 'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number', 'ack_count', 'syn_count', 'fin_count', 'rst_count', 'HTTP', 'HTTPS', 'DNS', 'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP', 'IPv', 'LLC', 'Tot sum', 'Min', 'Max', 'AVG', 'Std', 'Tot size', 'IAT', 'Number', 'Magnitue', 'Radius', 'Covariance', 'Variance', 'Weight', 'label', 'canonical_label', 'category']
['Header_Length', 'Protocol Type', 'Duration', 'Rate', 'Srate', 'Drate', 'fin_flag_number', 'syn_flag_number', 'rst_flag_number', 'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number', 'ack_count', 'syn_count', 'fin_count', 'rst_count', 'HTTP', 'HTTPS', 'DNS', 'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP', 'IPv', 'LLC', 'Tot sum', 'Min', 'Max', 'AVG', 'Std', 'Tot size', 'IAT', 'Number', 'Magnitue', 'Radius'

In [17]:
train_df["binary_label"] = train_df["category"].apply(
    lambda x: "Benign" if x == "Benign" else "Attack"
)

test_df["binary_label"] = test_df["category"].apply(
    lambda x: "Benign" if x == "Benign" else "Attack"
)


In [18]:
print(train_df["binary_label"].value_counts())
print(test_df["binary_label"].value_counts())

binary_label
Attack    6968099
Benign     192732
Name: count, dtype: int64
binary_label
Attack    1576575
Benign      37607
Name: count, dtype: int64


In [19]:
train_df.to_parquet("train_enriched.parquet")
test_df.to_parquet("test_enriched.parquet")

In [20]:
non_feature_cols = ["label", "canonical_label", "category", "binary_label"]

X_train = train_df.drop(columns=non_feature_cols)
y_train = train_df["binary_label"]
X_test = test_df.drop(columns=non_feature_cols)
y_test = test_df["binary_label"]

In [17]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced",
    n_jobs = -1,
    verbose = 2
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.


building tree 1 of 100building tree 4 of 100
building tree 7 of 100
building tree 8 of 100
building tree 3 of 100
building tree 10 of 100
building tree 2 of 100
building tree 9 of 100
building tree 12 of 100
building tree 11 of 100
building tree 5 of 100

building tree 6 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100


[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   48.7s


building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71

[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  3.1min finished
[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  17 tasks      | elapsed:    0.2s
[Parallel(n_jobs=12)]: Done 100 out of 100 | elapsed:    1.1s finished


Confusion Matrix:
 [[1575804     771]
 [   1772   35835]]

Classification Report:
               precision    recall  f1-score   support

      Attack       1.00      1.00      1.00   1576575
      Benign       0.98      0.95      0.97     37607

    accuracy                           1.00   1614182
   macro avg       0.99      0.98      0.98   1614182
weighted avg       1.00      1.00      1.00   1614182



In [19]:
import pandas as pd
importances = pd.Series(rf.feature_importances_, index=X_train.columns).sort_values(ascending=False)
print(importances.head(10))

Max                0.141083
Magnitue           0.130968
Variance           0.119871
AVG                0.094210
rst_count          0.090331
Tot size           0.075363
Header_Length      0.056332
Min                0.042370
psh_flag_number    0.034398
Weight             0.028477
dtype: float64


In [9]:
X_test_reset = X_test.reset_index(drop=True)
y_test_reset = y_test.reset_index(drop=True)
y_pred_series = pd.Series(y_pred).reset_index(drop=True)

misclassified = X_test_reset[y_test_reset != y_pred_series]
misclassified_true = y_test_reset[y_test_reset != y_pred_series]

# join back to the original label (not just binary) to see WHICH attack types get missed
test_df_reset = test_df.reset_index(drop=True)
missed_categories = test_df_reset.loc[misclassified.index, "category"].value_counts()
print(missed_categories)

NameError: name 'X_test' is not defined

In [21]:
import joblib
joblib.dump(rf, "rf_binary_full.joblib")

['rf_binary_full.joblib']

In [22]:
non_feature_cols = ["label", "canonical_label", "category", "binary_label"]

X_train = train_df.drop(columns=non_feature_cols)
y_train = train_df["category"]
X_test = test_df.drop(columns=non_feature_cols)
y_test = test_df["category"]
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced",
    n_jobs = -1,
    verbose = 2
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.


building tree 1 of 100building tree 3 of 100
building tree 12 of 100
building tree 7 of 100
building tree 4 of 100
building tree 6 of 100
building tree 5 of 100
building tree 9 of 100
building tree 10 of 100

building tree 2 of 100
building tree 8 of 100
building tree 11 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100


[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:  1.4min


building tree 30 of 100
building tree 31 of 100
building tree 32 of 100building tree 33 of 100

building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100building tree 53 of 100

building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71

[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  5.1min finished
[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  17 tasks      | elapsed:    0.5s
[Parallel(n_jobs=12)]: Done 100 out of 100 | elapsed:    2.8s finished


Confusion Matrix:
 [[  36602       0       0       0     568     437]
 [      5 1066662      93       2       2       0]
 [      0     182  416492       0       2       0]
 [    246       0       3   63447       1      18]
 [    613       0       0       1   27010      52]
 [    218       0       0       3      91    1432]]

Classification Report:
               precision    recall  f1-score   support

      Benign       0.97      0.97      0.97     37607
        DDoS       1.00      1.00      1.00   1066764
         DoS       1.00      1.00      1.00    416676
        MQTT       1.00      1.00      1.00     63715
       Recon       0.98      0.98      0.98     27676
    Spoofing       0.74      0.82      0.78      1744

    accuracy                           1.00   1614182
   macro avg       0.95      0.96      0.95   1614182
weighted avg       1.00      1.00      1.00   1614182



In [23]:
joblib.dump(rf, "rf_5class_full.joblib")

['rf_5class_full.joblib']

In [21]:
import json
sample_row = X_test.iloc[0].to_dict()
print(json.dumps(sample_row, indent=2))

{
  "Header_Length": 3609.0,
  "Protocol Type": 17.0,
  "Duration": 64.0,
  "Rate": 212.9614977723726,
  "Srate": 212.9614977723726,
  "Drate": 0.0,
  "fin_flag_number": 0.0,
  "syn_flag_number": 0.0,
  "rst_flag_number": 0.0,
  "psh_flag_number": 0.0,
  "ack_flag_number": 0.0,
  "ece_flag_number": 0.0,
  "cwr_flag_number": 0.0,
  "ack_count": 0.0,
  "syn_count": 0.0,
  "fin_count": 0.0,
  "rst_count": 0.0,
  "HTTP": 0.0,
  "HTTPS": 0.0,
  "DNS": 0.0,
  "Telnet": 0.0,
  "SMTP": 0.0,
  "SSH": 0.0,
  "IRC": 0.0,
  "TCP": 0.0,
  "UDP": 1.0,
  "DHCP": 0.0,
  "ARP": 0.0,
  "ICMP": 0.0,
  "IGMP": 0.0,
  "IPv": 1.0,
  "LLC": 1.0,
  "Tot sum": 3609.0,
  "Min": 154.8,
  "Max": 1228.4,
  "AVG": 610.0088888888888,
  "Std": 487.4092996797132,
  "Tot size": 673.2,
  "IAT": 169402747.0809622,
  "Number": 5.5,
  "Magnitue": 34.69535543626026,
  "Radius": 689.3008420338226,
  "Covariance": 279086.09952733683,
  "Variance": 0.9,
  "Weight": 38.5
}


In [1]:
import sklearn
print(sklearn.__version__)

1.7.2
